name: Build and Publish Blazor App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release

    - name: Publish Blazor App
      run: dotnet publish ./MyPortfolio.csproj -c Release -o publish

    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: BlazorApp
        path: publish
